### ISSUE TITLE
[Feature]: Add Google Image Search feature similar to Unsplash

### ISSUE THREAD

**Issue by drtobbyas** [inovector/MixpostProTeamApp#5]
It would be great if you could add the ability to use Google Image Search when adding media. 

From experience, Google Image Search provides better search quality and semblance to search terms than Unsplash. 
Unsplash is more suited for Stock Photos which most times do not relate to or convey the message you are trying to post.

Even though Google is a general-purpose Search Engine, Google Image Search returns good enough images that can be used for Twitter and other Social Media posts.

This is useful, especially for tech-related search terms for instance, if you search 'Kubernetes or Gitlab' in Unsplash, you will probably get unrelated Stock Photos or nothing. Google wins in these scenarios

Most times I have to do a Google search, find the image, download and upload to MixPost. Integrating Google Image Search can greatly improve this workflow.

**Comment by saschafoerster** [comment]
In professional context, I would NOT like this feature, as it would suggest to the teams using it, that you could take any image from the web without taking care of copyrights or licensing, which can easily lead to legal consequences. At least it should never be activated by default.

**Comment by drtobbyas** [comment]
Good observation though. It will be good If it can be available for those
who need it. Maybe a switch to turn on/off accompanied by a disclaimer
warning message would make it perfect.

**Comment by lao9s** [comment]
I do not plan to integrate Google Image Search.
